version: '3.8'

services:
  web:
    image: quilvian-postgre-api
    build: .
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres-container;Port=5432;Username=sa;Password=Admin@1234;Database=QuilvianSystemBackendDev
      - WhatsApp__ApiUrl=https://wa-staging.quilvian-mmchospital.com/send-message
      - WhatsApp__x-api-key=kynd_X2n91cA38Dz73k5Mf81aZLq8Ld_f9083da98dfd092a8c5
    
    depends_on:
      - postgres-container
    volumes:
      - ./wwwroot/images:/app/wwwroot/images
      - ./wwwroot/FotoDokter:/app/wwwroot/FotoDokter
      - ./wwwroot/FotoPasienBaru:/app/wwwroot/FotoPasienBaru
      - ./wwwroot/QRCodePasienBaru:/app/wwwroot/QRCodePasienBaru
      - ./wwwroot/scanktp:/app/wwwroot/scanktp
      # - ./wwwroot/TTDUser:/app/wwwroot/TTDUser
      # - ./wwwroot/TTDIGD:/app/wwwroot/TTDIGD

  postgres-container:
    image: postgres:13
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: Admin@1234
      POSTGRES_DB: QuilvianSystemBackendDev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

# cd /home/ecustomer/QuilvianSystemBackendDev-QuilvianDev/ (masuk kefolder)
# chmod -R 777 wwwroot/FotoDokter
# chmod -R 777 wwwroot/FotoPasienBaru
# chmod -R 777 wwwroot/QRCodePasienBaru
# chmod -R 777 wwwroot/images
# chmod -R 777 wwwroot/scanktp
