version: '3.8'

services:
  web:
    image: quilvian-postgre-api
    build: .
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres-container;Port=5432;Username=sa;Password=Admin@1234;Database=QuilvianSystemBackendDev
    depends_on:
      - postgres-container
    volumes:
      - ./wwwroot/images:/app/wwwroot/images
      - ./wwwroot/FotoDokter:/app/wwwroot/FotoDokter
      - ./wwwroot/FotoPasienBaru:/app/wwwroot/FotoPasienBaru
      - ./wwwroot/QRCodePasienBaru:/app/wwwroot/QRCodePasienBaru
      - ./wwwroot/scanktp:/app/wwwroot/scanktp

  postgres-container:
    image: postgres:13
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: Admin@1234
      POSTGRES_DB: QuilvianSystemBackendDev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
