// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuilvianSystemBackendDev.Repositories;

#nullable disable

namespace QuilvianSystemBackendDev.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Agama", b =>
                {
                    b.Property<Guid>("AgamaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("KodeAgama")
                        .HasColumnType("text");

                    b.Property<string>("NamaAgama")
                        .HasColumnType("text");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AgamaId");

                    b.ToTable("MstAgama", "public");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Asuransi", b =>
                {
                    b.Property<Guid?>("AsuransiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlamatCabang")
                        .HasColumnType("text");

                    b.Property<string>("AlamatPusat")
                        .HasColumnType("text");

                    b.Property<int?>("BatasMaxKlaimPerKunjungan")
                        .HasColumnType("integer");

                    b.Property<int?>("BatasMaxKlaimPerTahun")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("BatasWaktuPembayaran")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("BiayaTidakDitanggung")
                        .HasColumnType("integer");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("Createdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DokumenKlaim")
                        .HasColumnType("text");

                    b.Property<string>("EmailPerwakilan")
                        .HasColumnType("text");

                    b.Property<string>("EmailPusat")
                        .HasColumnType("text");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsPKS")
                        .HasColumnType("boolean");

                    b.Property<string>("JabatanPerwakilan")
                        .HasColumnType("text");

                    b.Property<string>("JenisAsuransi")
                        .HasColumnType("text");

                    b.Property<string>("KategoriAsuransi")
                        .HasColumnType("text");

                    b.Property<string>("KodeAsuransi")
                        .HasColumnType("text");

                    b.Property<string>("Layanan")
                        .HasColumnType("text");

                    b.Property<int?>("MasaTunggu")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxUsiaPasien")
                        .HasColumnType("integer");

                    b.Property<string>("MetodeKlaim")
                        .HasColumnType("text");

                    b.Property<string>("NamaAsuransi")
                        .HasColumnType("text");

                    b.Property<string>("NamaBank")
                        .HasColumnType("text");

                    b.Property<string>("NamaBankCabang")
                        .HasColumnType("text");

                    b.Property<string>("NamaPerusahaanAsuransi")
                        .HasColumnType("text");

                    b.Property<string>("NamaPerwakilan")
                        .HasColumnType("text");

                    b.Property<string>("NoHotlineDarurat")
                        .HasColumnType("text");

                    b.Property<string>("NoRekRumahSakit")
                        .HasColumnType("text");

                    b.Property<string>("NoTelepon")
                        .HasColumnType("text");

                    b.Property<string>("NoTeleponPerwakilan")
                        .HasColumnType("text");

                    b.Property<string>("ObatDitanggung")
                        .HasColumnType("text");

                    b.Property<int?>("PenaltiTerlambatBayar")
                        .HasColumnType("integer");

                    b.Property<int?>("PersentasiBiayaPertanggungan")
                        .HasColumnType("integer");

                    b.Property<string>("RSRekanan")
                        .HasColumnType("text");

                    b.Property<string>("StatusAsuransi")
                        .HasColumnType("text");

                    b.Property<int?>("TambahanTanggungan")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("TanggalAkhirKerjasama")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("TanggalMulaiKerjasama")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TermOfPayment")
                        .HasColumnType("text");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("WaktuKlaim")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AsuransiId");

                    b.ToTable("MstAsuransi", "public");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.CoveranAsuransi", b =>
                {
                    b.Property<Guid>("CoveranAsuransiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AsuransiId")
                        .HasColumnType("uuid");

                    b.Property<string>("Class")
                        .HasColumnType("text");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsPKS")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsSurgery")
                        .HasColumnType("boolean");

                    b.Property<string>("KodeCoveranAsuransi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaAsuransi")
                        .HasColumnType("text");

                    b.Property<string>("ServiceCode")
                        .HasColumnType("text");

                    b.Property<string>("ServiceCodeClass")
                        .HasColumnType("text");

                    b.Property<string>("ServiceDesc")
                        .HasColumnType("text");

                    b.Property<decimal?>("Tarif")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("TglBerakhir")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TglBerlaku")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CoveranAsuransiId");

                    b.HasIndex("AsuransiId");

                    b.ToTable("MstCoveranAsuransi", "public");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Departement", b =>
                {
                    b.Property<Guid>("DepartementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("JamBuka")
                        .HasColumnType("text");

                    b.Property<string>("JamTutup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KepalaDepartement")
                        .HasColumnType("text");

                    b.Property<string>("KodeDepartement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Layanan")
                        .HasColumnType("text");

                    b.Property<string>("Lokasi")
                        .HasColumnType("text");

                    b.Property<string>("NamaDepartement")
                        .HasColumnType("text");

                    b.Property<string>("Telepon")
                        .HasColumnType("text");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DepartementId");

                    b.ToTable("MstDepartement", "public");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Dokter", b =>
                {
                    b.Property<Guid>("DokterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FotoDokter")
                        .HasColumnType("text");

                    b.Property<string>("FotoPath")
                        .HasColumnType("text");

                    b.Property<string>("ImageBytes")
                        .HasColumnType("text");

                    b.Property<bool?>("IsAsuransi")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("JudulFileFoto")
                        .HasColumnType("text");

                    b.Property<string>("KdDokter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NmDokter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nohp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Str")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TglSip")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TglStr")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DokterId");

                    b.ToTable("MstDokter", "public");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.DokterPoli", b =>
                {
                    b.Property<Guid>("DokterPoliId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DokterId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("KodeDokterPoli")
                        .HasColumnType("text");

                    b.Property<string>("KodeDokterSubPoli")
                        .HasColumnType("text");

                    b.Property<string>("NamaDokter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaPoliKlinik")
                        .HasColumnType("text");

                    b.Property<string>("NamaSubPoli")
                        .HasColumnType("text");

                    b.Property<Guid?>("PoliId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubPoliId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DokterPoliId");

                    b.HasIndex("DokterId");

                    b.HasIndex("PoliId");

                    b.HasIndex("SubPoliId");

                    b.ToTable("DokterPolis");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.GolonganDarah", b =>
                {
                    b.Property<Guid>("GolonganDarahId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("KodeGolonganDarah")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaGolonganDarah")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GolonganDarahId");

                    b.ToTable("MstGolonganDarah", "public");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Identitas", b =>
                {
                    b.Property<Guid>("IdentitasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("JenisIdentitas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KodeIdentitas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdentitasId");

                    b.ToTable("MstIdentitas", "public");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Jabatan", b =>
                {
                    b.Property<Guid>("JabatanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("KodeJabatan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaJabatan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("JabatanId");

                    b.ToTable("MstJabatan", "public");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.JadwalPraktek", b =>
                {
                    b.Property<Guid>("JadwalPraktekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DokterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DokterPoliId")
                        .HasColumnType("uuid");

                    b.Property<string>("HariPraktek")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("JamBerakhir")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("JamMulai")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KodeJadwalPraktek")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxPasien")
                        .HasColumnType("integer");

                    b.Property<string>("NamaDokter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PoliId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubPoliId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WaktuPraktek")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("JadwalPraktekId");

                    b.HasIndex("DokterPoliId");

                    b.ToTable("MstJadwalPraktek", "public");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.KabupatenKota", b =>
                {
                    b.Property<Guid>("KabupatenKotaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("KodeKabupatenKota")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaKabupatenKota")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProvinsiId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("KabupatenKotaId");

                    b.HasIndex("ProvinsiId");

                    b.ToTable("MstKabupatenKota", "public");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.KategoriPeralatan", b =>
                {
                    b.Property<Guid>("KategoriPeralatanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("KodeKategoriPeralatan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaKategoriPeralatan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("KategoriPeralatanId");

                    b.ToTable("MstKategoriPeralatan", "public");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Keanggotaan", b =>
                {
                    b.Property<Guid>("KeanggotaanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("JenisKeanggotaan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JenisPromo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KodeKeanggotaan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("KeanggotaanId");

                    b.ToTable("MstKeanggotaan", "public");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Kecamatan", b =>
                {
                    b.Property<Guid>("KecamatanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("KabupatenKotaId")
                        .HasColumnType("uuid");

                    b.Property<string>("KodeKecamatan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaKecamatan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("KecamatanId");

                    b.HasIndex("KabupatenKotaId");

                    b.ToTable("MstKecamatan", "public");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Kelurahan", b =>
                {
                    b.Property<Guid>("KelurahanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("KecamatanId")
                        .HasColumnType("uuid");

                    b.Property<string>("KodeKelurahan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaKelurahan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("KelurahanId");

                    b.HasIndex("KecamatanId");

                    b.ToTable("MstKelurahan", "public");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Negara", b =>
                {
                    b.Property<Guid>("NegaraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("KodeNegara")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaNegara")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("NegaraId");

                    b.ToTable("MstNegara", "public");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Pekerjaan", b =>
                {
                    b.Property<Guid>("PekerjaanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("KodePekerjaan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaPekerjaan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PekerjaanId");

                    b.ToTable("MstPekerjaan", "public");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Pendidikan", b =>
                {
                    b.Property<Guid>("PendidikanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("KodePendidikan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaPendidikan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PendidikanId");

                    b.ToTable("MstPendidikan", "public");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Peralatan", b =>
                {
                    b.Property<Guid>("PeralatanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<Guid>("KategoriPeralatanId")
                        .HasColumnType("uuid");

                    b.Property<string>("KodePeralatan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Maintenance_status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaPeralatan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Operational_status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Purchase_date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PeralatanId");

                    b.HasIndex("KategoriPeralatanId");

                    b.ToTable("MstPeralatan", "public");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Persalinan", b =>
                {
                    b.Property<Guid>("PersalinanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnastesiPersalinan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BeratBayi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BidanPersalinan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CatatanPersalinan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DokterPersalinan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("JenisKelaminBayi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KategoriKamar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KodePersalinan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KomplikasiPersalinan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaAyah")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaBayi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaIbu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaKamar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaPersalinan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NoKamar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObservasiPersalinan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PanjangBayi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusBayi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubTindakanPersalinan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TTLBayi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TanggalPersalinan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TindakanPersalinan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipePersalinan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PersalinanId");

                    b.ToTable("MstPersalinan", "public");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Poliklinik", b =>
                {
                    b.Property<Guid>("PoliklinikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Deskripsi")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HariOperasional")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("JamBuka")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("JamTutup")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KepalaPoliklinik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KodePoliklinik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LayananPoliklinik")
                        .HasColumnType("text");

                    b.Property<string>("Lokasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaPoliklinik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telepon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PoliklinikId");

                    b.ToTable("MstPoliklinik", "public");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Position", b =>
                {
                    b.Property<Guid>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepartementId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("PositionCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PositionId");

                    b.HasIndex("DepartementId");

                    b.ToTable("MstPosition", "public");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Provinsi", b =>
                {
                    b.Property<Guid>("ProvinsiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("KodeProvinsi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaProvinsi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("NegaraId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProvinsiId");

                    b.HasIndex("NegaraId");

                    b.ToTable("MstProvinsi", "public");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.RolePosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PositionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AspNetGroupRole", "public");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.RoleUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PositionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AspNetUserRole", "public");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.SubPoli", b =>
                {
                    b.Property<Guid>("SubPoliId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Deskripsi")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HariOperasional")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("JamBuka")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("JamTutup")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KepalaSubPoli")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KodeSubPoli")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LayananSubPoli")
                        .HasColumnType("text");

                    b.Property<string>("Lokasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaSubPoli")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PoliId")
                        .HasColumnType("uuid");

                    b.Property<string>("Telepon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SubPoliId");

                    b.HasIndex("PoliId");

                    b.ToTable("MstSubPoli", "public");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Title", b =>
                {
                    b.Property<Guid>("TitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("KodeTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TitleId");

                    b.ToTable("MstTitle", "public");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.UserActive", b =>
                {
                    b.Property<Guid>("UserActiveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Handphone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("PlaceOfBirth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserActiveCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserActiveId");

                    b.ToTable("MstUserActive", "public");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.Pendaftaran.Models.PendaftaranPasien", b =>
                {
                    b.Property<Guid>("PendaftaranPasienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DokterPemeriksa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("Layanan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaLengkap")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NoIdentitas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NoRekamMedis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Penjamin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TanggalLahir")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TempatLahir")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PendaftaranPasienId");

                    b.ToTable("PdfPasien", "public");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.Pendaftaran.Models.PendaftaranPasienBaru", b =>
                {
                    b.Property<Guid>("PendaftaranPasienBaruId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgamaId")
                        .HasColumnType("uuid");

                    b.Property<string>("AlamatDarurat")
                        .HasColumnType("text");

                    b.Property<string>("AlamatDomisili")
                        .HasColumnType("text");

                    b.Property<string>("AlamatIdentitas")
                        .HasColumnType("text");

                    b.Property<string>("AlamatPerusahaan")
                        .HasColumnType("text");

                    b.Property<string>("Alergi")
                        .HasColumnType("text");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FotoName")
                        .HasColumnType("text");

                    b.Property<string>("FotoPath")
                        .HasColumnType("text");

                    b.Property<Guid?>("GolonganDarahId")
                        .HasColumnType("uuid");

                    b.Property<string>("HubunganAnak")
                        .HasColumnType("text");

                    b.Property<string>("HubunganPasien")
                        .HasColumnType("text");

                    b.Property<Guid>("IdentitasId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentitasOrangTua")
                        .HasColumnType("text");

                    b.Property<byte[]>("ImageBytes")
                        .IsRequired()
                        .HasColumnType("BYTEA");

                    b.Property<string>("InformasiSekolah")
                        .HasColumnType("text");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("JenisKelamin")
                        .HasColumnType("text");

                    b.Property<string>("JudulFileFoto")
                        .HasColumnType("text");

                    b.Property<Guid?>("KecKabId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("KelurahanId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("KewarganegaraanId")
                        .HasColumnType("uuid");

                    b.Property<string>("KodePasien")
                        .HasColumnType("text");

                    b.Property<string>("KodePos")
                        .HasColumnType("text");

                    b.Property<Guid?>("KotaId")
                        .HasColumnType("uuid");

                    b.Property<string>("NamaKontakDarurat")
                        .HasColumnType("text");

                    b.Property<string>("NamaLengkap")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaOrangTua")
                        .HasColumnType("text");

                    b.Property<string>("NamaPerusahaan")
                        .HasColumnType("text");

                    b.Property<Guid?>("NegaraId")
                        .HasColumnType("uuid");

                    b.Property<string>("NoIdentitas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NoIdentitasDarurat")
                        .HasColumnType("text");

                    b.Property<string>("NoRekamMedis")
                        .HasColumnType("text");

                    b.Property<string>("NoRekamMedisLama")
                        .HasColumnType("text");

                    b.Property<int?>("NoTelepon1")
                        .HasColumnType("integer");

                    b.Property<int?>("NoTelepon2")
                        .HasColumnType("integer");

                    b.Property<int?>("NoTelepon3")
                        .HasColumnType("integer");

                    b.Property<string>("NoTeleponDarurat")
                        .HasColumnType("text");

                    b.Property<int?>("NoTeleponPerusahaan")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PekerjaanId")
                        .HasColumnType("uuid");

                    b.Property<string>("PekerjaanOrangTua")
                        .HasColumnType("text");

                    b.Property<Guid?>("PendidikanTerakhirId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProvinsiId")
                        .HasColumnType("uuid");

                    b.Property<string>("QrCode")
                        .HasColumnType("text");

                    b.Property<string>("RiwayatOperasi")
                        .HasColumnType("text");

                    b.Property<string>("RiwayatPenyakit")
                        .HasColumnType("text");

                    b.Property<string>("RiwayatPenyakitKeluarga")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("StatusKewarganegaraan")
                        .HasColumnType("text");

                    b.Property<string>("Suku")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("TanggalLahir")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TempatLahir")
                        .HasColumnType("text");

                    b.Property<string>("TipePasien")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TitleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PendaftaranPasienBaruId");

                    b.ToTable("PdfPasienBaru", "public");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<string>("KodeUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NamaUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("QuilvianSystemBackendDev.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("QuilvianSystemBackendDev.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuilvianSystemBackendDev.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("QuilvianSystemBackendDev.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.CoveranAsuransi", b =>
                {
                    b.HasOne("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Asuransi", null)
                        .WithMany("CoveranAsuransis")
                        .HasForeignKey("AsuransiId");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.DokterPoli", b =>
                {
                    b.HasOne("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Dokter", "Dokter")
                        .WithMany("DokterPolis")
                        .HasForeignKey("DokterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Poliklinik", "Poliklinik")
                        .WithMany()
                        .HasForeignKey("PoliId");

                    b.HasOne("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.SubPoli", "SubPoli")
                        .WithMany()
                        .HasForeignKey("SubPoliId");

                    b.Navigation("Dokter");

                    b.Navigation("Poliklinik");

                    b.Navigation("SubPoli");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.JadwalPraktek", b =>
                {
                    b.HasOne("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.DokterPoli", "DokterPoli")
                        .WithMany("JadwalPraktek")
                        .HasForeignKey("DokterPoliId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DokterPoli");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.KabupatenKota", b =>
                {
                    b.HasOne("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Provinsi", "Provinsi")
                        .WithMany("KabupatenKotas")
                        .HasForeignKey("ProvinsiId");

                    b.Navigation("Provinsi");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Kecamatan", b =>
                {
                    b.HasOne("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.KabupatenKota", "KabupatenKota")
                        .WithMany("Kecamatan")
                        .HasForeignKey("KabupatenKotaId");

                    b.Navigation("KabupatenKota");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Kelurahan", b =>
                {
                    b.HasOne("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Kecamatan", "Kecamatan")
                        .WithMany("Kelurahan")
                        .HasForeignKey("KecamatanId");

                    b.Navigation("Kecamatan");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Peralatan", b =>
                {
                    b.HasOne("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.KategoriPeralatan", "KategoriPeralatans")
                        .WithMany()
                        .HasForeignKey("KategoriPeralatanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KategoriPeralatans");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Position", b =>
                {
                    b.HasOne("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Departement", "Departement")
                        .WithMany("Positions")
                        .HasForeignKey("DepartementId");

                    b.Navigation("Departement");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Provinsi", b =>
                {
                    b.HasOne("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Negara", "Negara")
                        .WithMany("Provinsi")
                        .HasForeignKey("NegaraId");

                    b.Navigation("Negara");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.SubPoli", b =>
                {
                    b.HasOne("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Poliklinik", "Poliklinik")
                        .WithMany("SubPolis")
                        .HasForeignKey("PoliId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poliklinik");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Asuransi", b =>
                {
                    b.Navigation("CoveranAsuransis");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Departement", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Dokter", b =>
                {
                    b.Navigation("DokterPolis");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.DokterPoli", b =>
                {
                    b.Navigation("JadwalPraktek");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.KabupatenKota", b =>
                {
                    b.Navigation("Kecamatan");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Kecamatan", b =>
                {
                    b.Navigation("Kelurahan");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Negara", b =>
                {
                    b.Navigation("Provinsi");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Poliklinik", b =>
                {
                    b.Navigation("SubPolis");
                });

            modelBuilder.Entity("QuilvianSystemBackendDev.Areas.ManajemenKesehatan.MasterData.Models.Provinsi", b =>
                {
                    b.Navigation("KabupatenKotas");
                });
#pragma warning restore 612, 618
        }
    }
}
