name: QuilvianProduction-Deploy

on:
  push:
    branches:
      - QuilvianProduction

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY_BACKEND_PRO }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_IP_BACKEND_PRO }} >> ~/.ssh/known_hosts

    - name: Deploy to Production Server
      run: |
        ssh ${{ secrets.SSH_USER_BACKEND }}@${{ secrets.SSH_IP_BACKEND_PRO }} << 'EOF'
        set -e

        cd ~/QuilvianProduction

        echo "📥 Update source code"
        git fetch origin
        git reset --hard origin/QuilvianProduction
        git clean -fd

        # ===== IMAGE VERSION =====
        IMAGE_TAG=$(date +%Y%m%d%H%M%S)
        IMAGE_NAME="quilvianproduction-backend:$IMAGE_TAG"
        CONTAINER_NAME="quilvianproduction-container"

        echo "🐳 Build Docker Image: $IMAGE_NAME"
        docker build --no-cache -t $IMAGE_NAME .

        echo "🛑 Stop old container"
        docker stop $CONTAINER_NAME || true
        docker rm $CONTAINER_NAME || true

        echo "🚀 Run new container"
        docker run -d \
          --name $CONTAINER_NAME \
          -e ASPNETCORE_ENVIRONMENT=Production \
          -p 4000:80 \
          --restart unless-stopped \
          --memory="3g" \
          --memory-swap="3g" \
          $IMAGE_NAME

        echo "🔍 Verify running image"
        docker inspect $CONTAINER_NAME --format='Container uses image: {{.Config.Image}}'

        echo "🧹 Cleanup old images (safe)"
        docker image prune -f

        echo "✅ Deployment Production DONE"
        EOF
